name       : perl-io
version    : '1.51'
release    : 13
source     :
    - https://cpan.metacpan.org/authors/id/T/TO/TODDR/IO-1.51.tar.gz : 5493ea55998728cd2b7ecb8234c58fb5d5df27098d0f07addca22444d7616ce0
homepage   : https://metacpan.org/pod/IO
license    : Artistic-1.0-Perl
summary    : IO::Socket - Object interface to socket communications
component  : programming.perl
description: |
    IO provides a simple mechanism to load several of the IO modules in one go.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
