name       : perl-io
version    : '1.42'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/T/TO/TODDR/IO-1.42.tar.gz : eec5cc33a6cddba8b5d2425b60752882add7e4d41b7431a0ea4dcd73cc1f8cca
homepage   : https://metacpan.org/pod/IO
license    : Artistic-Perl-1.0
summary    : IO::Socket - Object interface to socket communications
component  : programming.perl
description: |
    IO::Socket - Object interface to socket communications
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
