name       : perl-io
version    : 1.25
release    : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GB/GBARR/IO-1.25.tar.gz : 89790db8b9281235dc995c1a85d532042ff68a90e1504abd39d463f05623e7b5
homepage   : http://search.cpan.org/~gbarr/IO-1.25/lib/IO/Socket.pm
license    : Artistic-Perl-1.0
summary    : IO::Socket - Object interface to socket communications
component  : programming.perl
description: |
    IO::Socket - Object interface to socket communications
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
