name       : perl-io
version    : '1.39'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/T/TO/TODDR/IO-1.39.tar.gz : 4f0502e7f123ac824188eb8873038aaf2ddcc29f8babc1a0b2e1cd34b55a1fca
homepage   : http://search.cpan.org/~toddr/IO-1.39/
license    : Artistic-Perl-1.0
summary    : IO::Socket - Object interface to socket communications
component  : programming.perl
description: |
    IO::Socket - Object interface to socket communications
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
